# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         WWW-IstanbulTeknik
version:      0.01
version_from: lib/WWW/IstanbulTeknik.pm
installdirs:  site
requires:
    HTML::TableContentParser:      0.13
    LWP:                           5.76
    WWW::Mechanize:                1.02

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.21
